#!/usr/bin/env python
"""Generate a realistic XLSX fixture using the sibling python-xlsx library.

Writes tests/render-test/python-xlsx/workbook.xlsx — a small sales report
touching the features xlsxjs will want to render over the next few slices:

    * multiple data types (text, number, date, boolean, formula)
    * shared strings
    * merged header cells
    * custom column widths
    * fonts (bold header, italic footer)
    * fills (coloured header row)
    * borders on the data area
    * number formats (currency, percent, date)
    * a formula with a cached value (SUM)

Run with python-xlsx's venv so the `xlsx` package resolves:

    ~/code/python-xlsx/.venv/bin/python scripts/make-python-xlsx-fixture.py
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from xlsx import Workbook
from xlsx.cell.rich_text import CellRichText, InlineFont, TextBlock
from xlsx.styles import Alignment, Border, Color, Font, PatternFill, Side

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
OUT_DIR = REPO / "tests" / "render-test" / "python-xlsx"
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_PATH = OUT_DIR / "workbook.xlsx"


def main() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Sales"

    # Column widths (Excel char units).
    ws.column_dimensions["A"].width = 14
    ws.column_dimensions["B"].width = 22
    ws.column_dimensions["C"].width = 12
    ws.column_dimensions["D"].width = 10
    ws.column_dimensions["E"].width = 12

    # Row 1: merged title banner.
    ws["A1"] = "Q4 Sales Report"
    ws.merge_cells("A1:E1")
    ws["A1"].font = Font(name="Calibri", size=16, bold=True)
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")

    # Row 3: header row.
    headers = ["Date", "Customer", "Units", "Margin", "Revenue"]
    for col, value in enumerate(headers, start=1):
        cell = ws.cell(row=3, column=col, value=value)
        cell.font = Font(bold=True, color="FFFFFFFF")
        cell.fill = PatternFill(
            fill_type="solid", fgColor="FF1F4E79", bgColor="FF1F4E79"
        )
        cell.alignment = Alignment(horizontal="center")

    # Rows 4..6: data. Formula lives in column E and carries a cached value.
    rows = [
        (date(2026, 1, 14), "Acme",         120, 0.22,  1560.0),
        (date(2026, 1, 21), "Initech",       45, 0.18,   567.0),
        (date(2026, 2,  3), "Globex Corp.", 310, 0.27,  4123.5),
    ]
    thin = Side(border_style="thin", color="FF999999")
    data_border = Border(left=thin, right=thin, top=thin, bottom=thin)
    for r, (d, customer, units, margin, revenue) in enumerate(rows, start=4):
        ws.cell(row=r, column=1, value=d).number_format = "yyyy-mm-dd"
        ws.cell(row=r, column=2, value=customer)
        ws.cell(row=r, column=3, value=units)
        mcell = ws.cell(row=r, column=4, value=margin)
        mcell.number_format = "0.0%"
        revcell = ws.cell(row=r, column=5, value=revenue)
        revcell.number_format = '"$"#,##0.00'
        for c in range(1, 6):
            ws.cell(row=r, column=c).border = data_border

    # Row 8: totals — a SUM formula WITH a cached value so readers that don't
    # evaluate formulas still render the correct total. python-xlsx's Cell
    # exposes .cached_value for this; the writer emits both <f> and <v>.
    ws["B8"] = "Total"
    ws["B8"].font = Font(italic=True)
    total = sum(r[4] for r in rows)
    total_cell = ws["E8"]
    total_cell.value = "=SUM(E4:E6)"
    total_cell.cached_value = total
    total_cell.number_format = '"$"#,##0.00'
    total_cell.font = Font(bold=True)

    # Row 10: a theme-coloured subtitle. Color(theme=4) is "accent1" in the
    # Office default theme (usually a blue); tint darkens it 25% toward black.
    # xlsxjs should resolve theme=4 + tint via parseTheme / resolveColor.
    ws["A10"] = "Generated by xlsxjs demo build"
    ws["A10"].font = Font(italic=True, color=Color(theme=4, tint=-0.25))

    # Row 12: a rich-text cell with bold+coloured and italic runs. CellRichText
    # lets python-xlsx emit one <si> containing several <r>/<rPr> runs, which
    # exercises the rich-text path in the renderer.
    ws["A12"] = CellRichText([
        TextBlock(InlineFont(b=True, color="FFD00000"), "Warning: "),
        "margins include ",
        TextBlock(InlineFont(i=True), "discount"),
        " category pricing.",
    ])

    wb.save(str(OUT_PATH))
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
